### PR TITLE
Feature/initialize react and tailwind

### PR DESCRIPTION
**Pull request by arositen**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description
Initializes React app using Vite, and also initializes Tailwind CSS. I intentionally deleted css in App.css to avoid potentially conflicting styles in the future. 
In addition, my teammate info was added to the README file.

## QA Instructions, Screenshots, Recordings
run command: "npm run dev" in terminal, it should look like this:

image

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## [optional] What gif best describes this PR or how it makes you feel?

til

### CODE REVIEW

**Comment by yusuken1121** [comment]
Thank you for your work on this. I’ve reviewed the changes and everything looks good. Great job!

**Review by frosty8104 — COMMENTED** [review]
Looks good

**Review by yusuken1121 — APPROVED** [review]
Thank you :))
Looks great!

**Review by MatthewNeie — APPROVED** [review]

**Review by kristi-h — COMMENTED** [review]
Looks good!

**Review by kristi-h — APPROVED** [review]

**Pull request merged**
